// danskLearn shared IPA dataset for Danish words/verbs/kids vocabulary.
//
// Extracted from the publicly-shared "Danish Dictionary from Beginner to
// Fluent" Anki deck on AnkiWeb (deck ID 805471301). IPA transcriptions
// are factual linguistic data and not copyrightable. The Anki deck
// itself contained audio files we did NOT redistribute (some were
// scraped from ordnet.dk, which forbids redistribution).
//
// Keys are lowercase Danish words with the verb infinitive marker
// "at " stripped (so "være", not "at være"). DanskSpeech.lookupIpa()
// applies the same normalisation when looking up.
//
// Standalone files load this via <script src="ipa.js">; build.py
// inlines it once at the top of the merged scripts.

window.DanskIPA = {
  BANK: {
    "abe": "[ˈæːbə]",
    "acceptere": "[ɑgsεbˈteˀʌ]",
    "adskille": "[ˈaðˌsgelˀə], [ˈaðˌsgelˀəlsə], [ˈsεˀɐ̯ˌsgelˀd], [sebɑˈʁɑˀd]",
    "advare": "[ˈaðˌvɑˀɑ]",
    "af": "[a], [a]",
    "afbryde": "[awˌbʁyˀðə]",
    "afgive": "[ˈɑwˌgiˀ]",
    "aflevere": "[ˈɑwleˌveˀʌ]",
    "aflyse": "[ˈɑwˌlyˀsə], [ˈmεlə]",
    "afskaffe": "[ˈɑw,sgɑfə]",
    "afslutte": "[ˈɑwˌsludə], [ˈfæɐ̯di], [ˈfæɐ̯di,gɶːʌ], [ˈfulˌføˀʌ], [ˈgεnəmˌføˀʌ], [ˈuð,ʁadə], [ˈtɶɐ̯ˀn]",
    "aftensmad": "[ˈɑfdəns,mað], [ˈmeda]",
    "afvise": "[ˈɑwˌviˀsə], [ˈɑwˌslɔˀ]",
    "agurk": "[aˈguɐ̯g]",
    "albue": "[ˈalˌbuːə]",
    "alle": "[ˈalə]",
    "allerede": "[ˈaləˈʁεːðə]",
    "altid": "[ˈalˀˌtiðˀ], [ˈɑldʁi]",
    "ambassade": "[ɑmbaˈsæːðə], [ɑmbasaˈdøˀɐ̯]",
    "ambulance": "[ɑmbuˈlɑŋsə]",
    "ananas": "[ˈananas]",
    "anbefale": "[ˈanbeˌfæˀlə]",
    "and": "[ˈanˀ], [ˈanˀdʁεg], [ˈεleŋ]",
    "anholde": "[ˈanˌhʌlˀə]",
    "ankel": "[ˈɑŋˀgəl]",
    "ankomme": "[ˈanˌkʌmˀə]",
    "anse": "[ˈanˌseˀ]",
    "ansigt": "[ˈansegd], [ˈfjεˀs]",
    "ansætte": "[ˈanˌsεdə], [ˈhyːʌ]",
    "ansøgning": "[ˈanˌsøjˀneŋ]",
    "apotek": "[ɑboˈteˀg]",
    "appelsin": "[ɑbəlˈsiˀn]",
    "arbejde": "[ˈɑːˌbɑjˀdə]",
    "arm": "[ˈɑˀm]",
    "arrangere": "[ɑɑŋˈɕeˀʌ]",
    "at": "[ad]",
    "baby": "[ˈbεjbi]",
    "badekar": "[ˈbæːðə,kɑ], [ˈbʁuːsʌ], [ˈbað], [ˈbʁuːsʌ,bað], [ˈbæːðə], [ˈbʁuːsə]",
    "badeværelse": "[ˈbæːðə,væɐ̯ʌlsə], [toaˈlεd]",
    "bag": "[ˈbæˀj], [ˈbæˀjˌve]",
    "bage": "[ˈbæːjə], [ˈbɑgdə]",
    "banan": "[baˈnæˀn]",
    "band": "[ˈbæːnd]",
    "bange": "[ˈbɑŋə]",
    "bank": "[ˈbɑŋˀg]",
    "banke": "[ˈbɑŋgə]",
    "bar": "[ˈbɑˀ]",
    "bare": "[ˈbɑːɑ], [ˈliːə]",
    "barn": "[ˈbɑˀn], [ˈbɶɐ̯ˀn]",
    "barndom": "[ˈbɑːnˌdʌmˀ]",
    "batteri": "[badʌˈʁiˀ]",
    "begrænse": "[beˈgʁanˀsə]",
    "begynde": "[beˈgønˀə], [ˈsdɑːdə], [ˈenˌleˀðə], [ˈpʌ,begønˀə]",
    "behandle": "[beˈhanˀlə]",
    "beholde": "[beˈhʌlˀə]",
    "behøve": "[beˈhøˀvə]",
    "beige": "[ˈbεːɕ]",
    "beklage": "[beˈklæˀjə], [ˈɔnˌsgylˀə]",
    "bemærke": "[beˈmæɐ̯gə], [ˈεnsə]",
    "ben": "[ˈbeˀn], [ˈlεˀg], [ˈlɒˀ]",
    "beskrive": "[beˈsgʁiˀvə]",
    "beskytte": "[beˈsgødə]",
    "bestille": "[beˈsdelˀə], [ˈbugə], [ʁεsæɐ̯ˈveˀʌ]",
    "bestå": "[beˈsdɔˀ], [ˈʌm,fadə], [enkluˈdeˀʌ], [ˈenəˌhʌlˀə]",
    "besøge": "[beˈsøˀjə]",
    "betale": "[beˈtæˀlə]",
    "betyde": "[beˈtyˀðə]",
    "bi": "[ˈbiˀ]",
    "bibliotek": "[biblioˈteˀg]",
    "bibliotekar": "[bibliotəˈkɑˀ]",
    "bide": "[ˈbiːðə]",
    "bidrage": "[ˈbiˌdʁɑˀwə]",
    "bil": "[ˈbiˀl], [ˈεl,biˀl]",
    "billede": "[ˈbeləðə], [ˈfoto]",
    "billet": "[beˈlεd]",
    "billig": "[ˈbili]",
    "binde": "[ˈbenə]",
    "biograf": "[bioˈgʁɑˀf]",
    "bjerg": "[ˈbjæɐ̯ˀw]",
    "bjørn": "[ˈbjɶɐ̯ˀn]",
    "blad": "[ˈblað]",
    "blande": "[ˈblanə]",
    "blive": "[ˈbliːə], [ˈbliɐ̯ˀ], [ˈbleˀ], [ˈbleːəð]",
    "blomst": "[ˈblʌmsd], [ˈblʌmsdʁʌ]",
    "bo": "[ˈboˀ], [ˈleːvə]",
    "bord": "[ˈboˀɐ̯]",
    "borger": "[ˈbɒːwʌ]",
    "bred": "[ˈbʁεðˀ]",
    "bringe": "[ˈbʁεŋə]",
    "bro": "[ˈbʁoˀ]",
    "bryst": "[ˈbʁœsd], [ˈbʁœsd,kasə], [ˈbɑˀm]",
    "brød": "[ˈbʁœðˀ], [ˈʁuˌbʁœðˀ]",
    "brønd": "[ˈbʁɶnˀ]",
    "bukser": "[ˈbɔgsʌ]",
    "bus": "[ˈbus]",
    "busstoppested": "[ˈsdʌbə,sdεð]",
    "butik": "[buˈtig]",
    "by": "[ˈbyˀ]",
    "bygge": "[ˈbygə]",
    "bytte": "[ˈbydə], [ˈbydneŋ], [ˈʌm,bydə], [ˈʌm,bydneŋ]",
    "båd": "[ˈbɔˀð]",
    "bælte": "[ˈbεldə], [ˈʁamˀ], [ˈseːlə], [ˈliw,ʁamˀ], [ˈseːlʌ]",
    "bære": "[ˈbεːʌ], [ˈbɑˀ], [ˈbɒːɒð]",
    "café": "[kaˈfeˀ]",
    "centrum": "[ˈsεntʁɔm]",
    "chance": "[ˈɕɑŋsə]",
    "chef": "[ˈɕεˀf]",
    "citron": "[siˈtʁoˀn]",
    "computer": "[kʌmˈpjuːdʌ]",
    "cykel": "[ˈsygəl]",
    "cykling": "[ˈsygleŋ]",
    "dag": "[ˈdæˀ]",
    "dal": "[ˈdæˀl]",
    "danse": "[ˈdansə], [ˈdanˀs]",
    "datter": "[ˈdadʌ], [ˈdødʁʌ]",
    "del": "[ˈdeˀl]",
    "dele": "[ˈdeːlə]",
    "delfin": "[dεlˈfiˀn]",
    "der": "[dɑ]",
    "derefter": "[ˈdεˀɐ̯ˌεfdʌ]",
    "desværre": "[deˈsvæɐ̯ʌ]",
    "digt": "[ˈdegd]",
    "direkte": "[ˈdiˈʁagdə]",
    "diskutere": "[disguˈteˀʌ], [ˈdʁœfdə]",
    "dominere": "[domiˈneˀʌ]",
    "dreje": "[ˈdʁɑjə]",
    "dreng": "[ˈdʁaŋˀ]",
    "drikke": "[ˈdʁεgə], [ˈdʁɑg], [ˈdʁɔgəð]",
    "dræbe": "[ˈdʁεːbə], [ˈslɒˀ iˈjεl]",
    "dukke": "[ˈdɔgə]",
    "dyr": "[ˈdyɐ̯ˀ]",
    "dække": "[ˈdεgə]",
    "døgn": "[ˈdʌjˀn]",
    "dør": "[ˈdɶˀɐ̯]",
    "edderkop": "[ˈεðˀʌˌkʌb]",
    "efter": "[ˈεfdʌ]",
    "egern": "[ˈeˀjʌn]",
    "eje": "[ˈɑjʌ]",
    "eksamen": "[εgˈsæːmən]",
    "eksempel": "[εgˈsεmˀbəl]",
    "eksistere": "[εgsiˈsdeˀʌ]",
    "elefant": "[eləˈfanˀd]",
    "elevator": "[eləˈvæːtʌ]",
    "elg": "[ˈεlˀj]",
    "ellers": "[ˈεlˀʌs]",
    "elske": "[ˈεlsgə]",
    "en": "[ˈsvɑmˀb]",
    "ende": "[ˈεnə], [ˈnɔmsə], [ˈʁɶwˀ], [ˈbalə]",
    "erfaring": "[æɐ̯ˈfɑˀeŋ]",
    "erstatte": "[æɐ̯ˈsdadə], [ˈsgifdə]",
    "evne": "[ˈεwnə]",
    "falde": "[ˈfalə]",
    "familie": "[faˈmilˀjə]",
    "fange": "[ˈfɑŋə]",
    "far": "[ˈfɑː]",
    "farlig": "[ˈfɑːli], ['ufɑːli], [ˈfɑːɑˌtʁuˀənə], [ˈtʁœg], [ˈuˌtʁœg]",
    "fart": "[ˈfɑˀd], [ˈhasdiˌheðˀ]",
    "farve": "[ˈfɑːvə]",
    "feber": "[ˈfeˀbʌ]",
    "fejre": "[ˈfɑjʁʌ]",
    "fersken": "[ˈfæɐ̯sgən]",
    "fest": "[ˈfεsd]",
    "fil": "[ˈfiˀl], [ˈlyðfiˀl]",
    "film": "[ˈfilˀm]",
    "finde": "[ˈfenə], [ˈfɔnˀ]",
    "finger": "[ˈfeŋˀʌ]",
    "fjerne": "[ˈfjæɐ̯nə]",
    "fjernsyn": "[ˈfjæɐ̯nˌsyˀn], [ˈteˀˌveˀ]",
    "flagermus": "[ˈflɑwʌˌmuˀs]",
    "fly": "[ˈflyˀ], [ˈflyːvə,maˈsgiːnə]",
    "flygte": "[ˈfløgdə]",
    "flygtning": "[ˈfløgdneŋ]",
    "flytte": "[ˈflødə]",
    "flyve": "[ˈflyːvə], [ˈflʌjˀ]",
    "fod": "[ˈfoˀð]",
    "fodbold": "[ˈfoðˌbʌlˀd]",
    "fodre": "[ˈfoðʁʌ]",
    "foran": "[ˈfɒːˈanˀ]",
    "forberede": "[ˈfɒːbeˌʁεðˀə]",
    "forbinde": "[fʌˈbenˀə]",
    "foregå": "[ˈfɒːɒˌgɔˀ]",
    "forekomme": "[ˈfɒːɒˌkʌmˀə], [ˈviɐ̯gə], [ˈsynəs], [ˈlɑ]",
    "foreslå": "[ˈfɒːɒˌslɔˀ]",
    "foretrække": "[ˈfɒːɒtʁagə], [pʁεfəˈʁεˀʌ]",
    "forhandle": "[fʌˈhanˀlə]",
    "forhindre": "[fʌˈhenˀdʁʌ], [ˈhenˀdʁʌ], [ˈfɒːɒˌbygə]",
    "forhold": "[ˈfɒːˌhʌlˀ], [ʁεlaˈɕoˀn], [ˈpɑ,fɒːˌhʌlˀ]",
    "forkert": "[fʌˈkeɐ̯ˀd], [ˈgæˀl]",
    "forklare": "[fʌˈklɑˀɑ]",
    "forlade": "[fʌˈlæˀðə], [aˈsdεð], [ ‘εfdʌˌlæˀðə]",
    "form": "[ˈfɒˀm]",
    "formulere": "[fɒmuˈleˀʌ]",
    "forsvare": "[fʌˈsvɑˀɑ]",
    "forsvinde": "[fʌˈsvenˀə]",
    "fortjene": "[fʌˈtjεˀnə]",
    "fortov": "[ˈfɒːˌtɒw]",
    "fortsætte": "[ˈfɒːdˌsεdə]",
    "forvandle": "[fʌˈvanˀlə]",
    "forvente": "[fʌˈvεnˀdə], [ˈfɒuðˌsiˀə], [fʌˈvεnˀdneŋ], [ˈfɒuðˌsiˀəlsə]",
    "forår": "[ˈfɒːˌɒˀ], [ˈεfdʌˌɒˀ]",
    "frakke": "[ˈfʁɑgə]",
    "fremmed": "[ˈfʁaməð]",
    "fremstille": "[ˈfʁamˌsdelˀə]",
    "frihed": "[ˈfʁiˌheðˀ], [beˈfʁiˀəlsə]",
    "frugt": "[ˈfʁɔgd]",
    "frygte": "[ˈfʁœgdə], [ˈbɑŋə], [ˈsgʁamə], [fʌˈsgʁagə]",
    "fugl": "[ˈfuˀl]",
    "fuld": "[ˈfulˀ], [ˈmεd]",
    "fylde": "[ˈfylə]",
    "fyre": "[ˈfyːʌ]",
    "få": "[ˈfɔˀ], [ˈsgɑfə], [ˈmoðˌtæˀ], [ˈhεndə], [æɐ̯ˈvæɐ̯ˀvə], [ˈanˌsgɑfə]",
    "får": "[ˈfɒˀ], [ˈlɑmˀ]",
    "fængsel": "[ˈfεŋˀsəl]",
    "færge": "[ˈfæɐ̯wə]",
    "fætter": "[ˈfεdʌ], [kuˈsiːnə]",
    "føde": "[ˈføːðə]",
    "følelse": "[ˈføːləlsə]",
    "følge": "[ˈføljə]",
    "føre": "[ˈføːʌ], [ˈanˌføˀʌ]",
    "gade": "[ˈgæːðə], [ˈvɑjˀ], [buləˈvɑˀd], [avəˈny], [aˈleˀ]",
    "gammel": "[ˈgɑməl], [ˈεldʁʌ], [ˈεlˀsd]",
    "gardin": "[gɑˈdiˀn]",
    "gavmild": "[ˈgɑwˌmilˀ]",
    "generation": "[genəʁɑˈɕoˀn]",
    "genere": "[ɕeˈneˀʌ], [iɐ̯iˈteˀʌ], [ˈʌb,hisə], [beˈlεmˀʁʌ], [uˈlɑjˀˌliˀə], [beˈsvεˀʌ]",
    "generel": "[genəˈʁɑˀl]",
    "genert": "[ɕeˈneɐ̯ˀd], [ˈsgyˀ]",
    "gennemføre": "[ˈgεnəmˌføˀʌ]",
    "gennemgå": "[ˈgεnəmˌgɔˀ]",
    "gentage": "[ˈgεntæ], [ˈgεntɑˀ], [ˈgεntoˀ], [ˈgεntæəð]",
    "gide": "[ˈgiːðə]",
    "giraf": "[giˈʁɑf]",
    "give": "[ˈgiˀ], [ˈgiɐ̯ˀ], [ˈgæˀ], [ˈgiːəð]",
    "glemme": "[ˈglεmə]",
    "glide": "[ˈgliːðə], [ˈslebə]",
    "god": "[ˈgoˀ], [ˈgʌd], [ˈbεðʁʌ], [ˈbεsd]",
    "godkende": "[ˈgoðˌkεnˀə], [ɑwtoɐ̯iˈseˀʌ]",
    "gratis": "[ˈgʁɑːdis], [ˈfʁiˀ]",
    "gribe": "[ˈgʁiːbə]",
    "grim": "[ˈgʁεmˀ], [ˈhεsli]",
    "grine": "[ˈgʁiːnə], [ˈleˀ]",
    "gris": "[ˈgʁiˀs], [ˈsviˀn]",
    "græde": "[ˈgʁaːðə], [ˈtuːðə]",
    "grøntsag": "[ˈgʁɶnˌsæˀj]",
    "guld": "[ˈgul], [ˈsøl]",
    "gulerod": "[ˈguləˌʁoˀð]",
    "gulv": "[ˈgɔl]",
    "gæst": "[ˈgεsd]",
    "had": "[ˈhað]",
    "hade": "[ˈhæːðə]",
    "hage": "[ˈhæːjə], [ˈpanə]",
    "hals": "[ˈhalˀs], [ˈnɑgə]",
    "handle": "[ˈhanlə]",
    "hat": "[ˈhad]",
    "hav": "[ˈhɑw]",
    "have": "[ˈha], [ˈhɑˀ], [ˈhæːðə], [ˈhɑfd]",
    "havn": "[ˈhɑwˀn]",
    "heldigvis": "[ˈhεldiˈviˀs]",
    "helikopter": "[hεliˈkʌbdʌ]",
    "helligdag": "[ˈhεliˌdæˀ]",
    "helt": "[ˈhεlˀd]",
    "hente": "[ˈhεndə]",
    "henvende sig": "[-ˌvεnˀə]",
    "her": "[ˈhεˀɐ̯]",
    "herske": "[ˈhæɐ̯sgə], [ʁεˈgeˀʌ]",
    "hest": "[ˈhεsd]",
    "hilse": "[ˈhilsə]",
    "hinanden": "[hiˈnanən]",
    "historie": "[hiˈsdoɐ̯ˀiə]",
    "hjemmeside": "[ˈjεmə,siːðə]",
    "hjort": "[ˈjɒːd], [ˈdyɐ̯ˀ]",
    "hjælpe": "[ˈjεlbə]",
    "hofte": "[ˈhʌfdə]",
    "holde": "[ˈhʌlə]",
    "hoppe": "[ˈhʌbə], [ˈsbʁεŋə]",
    "hospital": "[hɔsbiˈtæˀl]",
    "hoste": "[ˈhoːsdə]",
    "hotel": "[hoˈtεlˀ]",
    "hoved": "[ˈhoːəð], [ˈhoːəð], [ˈhoːðʌ]",
    "hud": "[ˈhuðˀ]",
    "hue": "[ˈhuːə]",
    "hund": "[ˈhunˀ], [ˈvalˀb]",
    "hus": "[ˈhuˀs]",
    "huske": "[ˈhusgə]",
    "hvad hedder du?": "[ˈheðə]",
    "hval": "[ˈvæˀl]",
    "hviske": "[ˈvesgə]",
    "hylde": "[ˈhylə]",
    "håb": "[ˈhɔˀb]",
    "håbe": "[ˈhɔːbə]",
    "hånd": "[ˈhʌnˀ], [ˈhεnˀʌ]",
    "hår": "[ˈhɒˀ]",
    "hård": "[ˈhɒˀ], [ˈbløˀð]",
    "hæl": "[ˈhεˀl]",
    "hælde": "[ˈhεlə]",
    "hænge": "[ˈhεŋə], [ˈhɑŋˀ]",
    "høj": "[ˈlεːsə], [ˈhʌjˀ]",
    "høne": "[ˈhœːnə], [ˈhæːnə]",
    "høre": "[ˈhøːʌ]",
    "i": "[i]",
    "i aften": "[ˈɑfdən]",
    "i dag": "[ˈdæˀ], [ˈgɒˀ], [ˈfɒːˌgɒˀs], [ˈmɒɒn], [ˈɒwˀʌˈmɒɒn]",
    "idé": "[iˈdeˀ]",
    "indebære": "[ˈenəˌbεˀʌ]",
    "indeholde": "[ˈenəˌhʌlˀə]",
    "indføre": "[ˈenˌføˀʌ]",
    "indrette": "[ˈenˌʁadə]",
    "indrømme": "[ˈenˀ,ʁɶmˀə], [ˈmεðˌgiˀ]",
    "ingen": "[ˈeŋən], [ˈendəð]",
    "insekt": "[enˈsεgd]",
    "investere": "[envəˈsdeˀʌ], [envəˈsdeˀɐ̯eŋ]",
    "invitere": "[enviˈteˀʌ]",
    "irritere": "[iɐ̯iˈteˀʌ]",
    "is": "[ˈiˀs]",
    "jakke": "[ˈjɑgə]",
    "job": "[ˈdjʌb], [ˈɑːˌbɑjˀdə]",
    "jord": "[ˈjoˀɐ̯]",
    "jordbær": "[ˈjoɐ̯ˌbæɐ̯], [ˈtʁɑːnəˌbæɐ̯], [ˈhenˌbæɐ̯], [ˈblʌˌbæɐ̯], [ˈbʁɔmˌbæɐ̯], [ˈkiɐ̯səˌbæɐ̯]",
    "kage": "[ˈkæːjə]",
    "kalde": "[ˈkalə], [ˈʁεŋə]",
    "kamera": "[ˈkæˀməʁɑ]",
    "kanin": "[kaˈniˀn]",
    "karakter": "[kɑɑgˈteˀɐ̯]",
    "karriere": "[kɑiˈεːʌ]",
    "kartoffel": "[kɑˈtʌfəl]",
    "kat": "[ˈkad], [ˈkileŋ]",
    "ked af det": "[ˈkeðˀ], [ˈɔnˌsgylˀ]",
    "kigge": "[ˈkigə], [ˈseˀ], [ˈsøːjə], [ˈleːðə]",
    "kiks": "[ˈkigs]",
    "kind": "[ˈkenˀ]",
    "kirke": "[ˈkiɐ̯gə]",
    "kjole": "[ˈkjoːlə]",
    "klare": "[ˈklɑːɑ], [ˈmɑgdə]",
    "klatre": "[ˈkladʁʌ]",
    "knogle": "[ˈknɒwlə], [ˈbeˀn]",
    "knytte": "[ˈknydə]",
    "knæ": "[ˈknεˀ]",
    "ko": "[ˈkoˀ], [ˈkalˀv]",
    "kodeord": "[ˈkoːðə,oˀɐ̯], [ˈpɑːsˌwœːd]",
    "koge": "[ˈkɔːwə]",
    "kollega": "[koˈleːga]",
    "kombinere": "[kʌmbiˈneˀʌ]",
    "komme": "[ˈkʌmə]",
    "kommentere": "[kɔmənˈteˀʌ]",
    "kompleks": "[kʌmbliˈseˀʌ]",
    "koncert": "[kɔnˈsæɐ̯d]",
    "konsekvens": "[kʌnsəˈkvεnˀs], [ˈføljə]",
    "kontakte": "[kɔnˈtɑgdə]",
    "kontor": "[kɔnˈtoˀɐ̯]",
    "kontrollere": "[kʌntʁoˈleˀʌ]",
    "kort": "[ˈkɒːd]",
    "koste": "[ˈkɔsdə]",
    "krig": "[ˈkʁiˀ]",
    "kritisere": "[kʁidiˈseˀʌ], [ˈneð,sæˀblə]",
    "krop": "[ˈkʁʌb], [beˈvεˀjəlsə]",
    "kræve": "[ˈkʁεːvə]",
    "kultur": "[kulˈtuɐ̯ˀ]",
    "kun": "[ˈkɔn], [ˈbɑːɑ], [ˈblʌd]",
    "kvarter": "[kvɑˈteˀɐ̯], [ˈnæːboˌlæˀj]",
    "kvinde": "[ˈkvenə]",
    "kylling": "[ˈkyleŋ]",
    "kysse": "[ˈkøsə]",
    "kyst": "[ˈkøsd]",
    "kæmpe": "[ˈkεmbə]",
    "kæreste": "[ˈkæɐ̯ʌsdə]",
    "kærlighed": "[ˈkæɐ̯liˌheðˀ]",
    "købe": "[ˈkøːbə]",
    "kød": "[ˈkøð]",
    "køkken": "[ˈkøgən]",
    "køleskab": "[ˈkøːlə,sgæˀb]",
    "køre": "[ˈkøːʌ]",
    "lade": "[ˈla], [ˈlɑ], [ˈloðˀ], [ˈlad], [ˈteˌlæˀðə], [ˈte,loðˀ], [ˈte,lad]",
    "laks": "[ˈlɑgs], [ˈtuˀn]",
    "land": "[ˈlanˀ]",
    "langs": "[ˈlɑŋˀs]",
    "langsom": "[ˈlɑŋˌsʌmˀ], [ˈhoɐ̯di]",
    "lastbil": "[ˈlasdbiˀl], [pigˈʌb], [ˈlað]",
    "lav": "[ˈlɑw]",
    "lave": "[ˈlæːvə], [ˈgɶːʌ]",
    "lede": "[ˈleːðə]",
    "leg": "[ˈlɑjˀ], [ˈsbel]",
    "lege": "[ˈlɑjə]",
    "legetøj": "[ˈlɑjəˌtʌj]",
    "lejlighed": "[ˈlɑjliˌheðˀ]",
    "lektier": "[ˈlεgɕə]",
    "lette": "[ˈlεdə]",
    "levende": "[ˈleːvənə]",
    "lide": "[ˈliːðə]",
    "lidt": "[ˈlid]",
    "lighed": "[ˈliːˌheðˀ], [ˈfɒːˌsgεlˀ]",
    "ligne": "[ˈliːnə]",
    "loft": "[ˈlʌfd]",
    "lokke": "[ˈlʌgə]",
    "love": "[ˈlɔːwə], [ˈløfdə]",
    "luft": "[ˈlɔfd], [ˈilˀd], [ʌgsyˈgeˀn]",
    "lufthavn": "[ˈlɔfdˌhɑwˀn]",
    "lukke": "[ˈlɔgə], [ˈɔːbnə]",
    "lunge": "[ˈlɔŋə]",
    "lyde": "[ˈlyːðə], [ˈløðˀ], [ˈlyd]",
    "lykkes": "[ˈløgəs], [ˈmisˌløgəs]",
    "lys": "[ˈlyˀs]",
    "lyserød": "[ˈlysəʁœðˀ], [ˈpeŋg]",
    "lytte": "[ˈlydə]",
    "låne": "[ˈlɔːnə]",
    "læbe": "[ˈlεːbə]",
    "lægge": "[ˈlεgə], [plaˈseˀʌ], [ˈsdelə], [ˈpudə], [ˈsεdə], [ˈlegə]",
    "lære": "[ˈlεːʌ]",
    "lærer": "[ˈlεːʌ], [ˈɔnʌˌviˀsʌ], [pεdaˈgoˀ]",
    "læse": "[ˈlεːsə]",
    "løbe": "[ˈløːbə]",
    "løfte": "[ˈløfdə]",
    "løgn": "[ˈlʌjˀn], [ˈlʌjnʌ]",
    "løn": "[ˈlœnˀ]",
    "løse": "[ˈløːsə]",
    "løsning": "[ˈløːsneŋ]",
    "løve": "[ˈløːvə]",
    "majs": "[ˈmɑjˀs], [ˈmɑjˀs,kʌlbə]",
    "male": "[ˈmæːlə], [ˈmæːlʌ], [ˌmæːlʌˈʁiˀ], [ˈmæːleŋ], [ˈmæːlə], [ˈmæːləð]",
    "mand": "[ˈmanˀ], [ˈmεnˀ]",
    "mangle": "[ˈmɑŋlə]",
    "mappe": "[ˈmɑbə]",
    "marked": "[ˈmɑːgəð]",
    "mave": "[ˈmæːvə]",
    "med": "[mε]",
    "medicin": "[mediˈsiˀn]",
    "mellem": "[ˈmεləm]",
    "mening": "[ˈmeːneŋ]",
    "mere": "[ˈmeːʌ]",
    "metro": "[ˈmeːtʁo], [ˈɔnʌgʁɔns,bæːnə]",
    "middag": "[ˈmeda]",
    "midnat": "[ˈmiðˌnad]",
    "militær": "[miliˈtεˀɐ̯]",
    "minde": "[ˈmenə], [eˈʁεnˀdʁεŋ]",
    "minister": "[miˈnisdʌ]",
    "minut": "[meˈnud]",
    "mod": "[ˈmoˀð]",
    "moden": "[ˈmoˀðən]",
    "mor": "[ˈmoɐ̯], [ˈmøðʁʌ]",
    "motorcykel": "[ˈmoːtʌˌsygəl]",
    "mulig": "[ˈmuːli], [uˈmuˀli], [ˈmuːliˈviˀs]",
    "mulighed": "[ˈmuːliˌheðˀ]",
    "mund": "[ˈmɔnˀ]",
    "musik": "[muˈsig], [ˈmuˀsigʌ]",
    "muskel": "[ˈmusgəl]",
    "mål": "[ˈmɔˀl]",
    "måle": "[ˈmɔːlə]",
    "måne": "[ˈmɔːnə]",
    "måned": "[ˈmɔːnəð]",
    "måske": "[mɔˈsgeˀ]",
    "måtte": "[ˈmɔˀ]",
    "mælk": "[ˈmεlˀg]",
    "møde": "[ˈmøːðə]",
    "nabo": "[ˈnæːbo]",
    "nat": "[ˈnad], [ˈnεdʌ]",
    "natur": "[naˈtuɐ̯ˀ]",
    "navn": "[ˈnɑwˀn]",
    "nederdel": "[ˈneðʌ,deˀl]",
    "nedlægge": "[ˈneð,lεgə]",
    "nem": "[ˈnεmˀ], [ˈlεd], [ˈliːəˈtel], [ˈsemˀbəl], [ˈukʌmbliˌseˀʌð], [ˈεŋˀgəl]",
    "nevø": "[neˈvø], [niˈεːsə]",
    "nikke": "[ˈnegə]",
    "nogen": "[ˈnoən], [ˈnɔːəð], [ˈnoən], [ˈnɔːəð]",
    "nu": "[ˈnu]",
    "nummer": "[ˈnɔmˀʌ], [ˈtal]",
    "ny": "[ˈnyˀ]",
    "nyde": "[ˈnyːðə], [ˈnøðˀ], [ˈnyd]",
    "nysgerrig": "[ˈnysˌgæɐ̯ˀi]",
    "nå": "[ˈnɒˀ]",
    "når": "[nɒ], [ˈda]",
    "nægte": "[ˈnεgdə]",
    "næse": "[ˈnεːsə], [ˈøːʌ]",
    "næste": "[ˈnεsdə], [ˈsiðən]",
    "næsten": "[ˈnεsdən]",
    "nøgle": "[ˈnʌjlə]",
    "officiel": "[ʌfiˈɕεlˀ]",
    "ofte": "[ˈʌfdə], [ˈtid], [ˈhybid], [ˈsʌməˈtiðʌ], [ˈnoən ˈgɑŋə], [ˈɕεlənd]",
    "og": "[ˈɒw]",
    "også": "[ˈʌs], [ˈliːəˌleːðəs]",
    "olie": "[ˈoljə]",
    "opdage": "[ˈʌbˌdæˀjə]",
    "operation": "[obəʁɑˈɕoˀn], [kiˈʁuɐ̯ˀw]",
    "operere": "[obəˈʁεˀʌ]",
    "opfatte": "[ˈʌb,fadə]",
    "opfinde": "[ˈʌbˌfenˀə]",
    "opfordre": "[ˈʌbˌfɒˀdʁʌ]",
    "opfylde": "[ˈʌbˌfylˀə], [en,fʁiˀ], [ˈleːvə]",
    "opgave": "[ˈʌbˌgæːvə]",
    "ophæve": "[ˈʌbˌhεˀvə], [ˈʌbˌhεˀvəlsə], [ˈʌbˌsiˀə], [ˈʌbˌsiˀəlsə], [anuˈleˀʌ], [anulaˈɕoˀn], [ˈɑwbeˌsdelˀə], [ˈɑwbeˌsdelˀeŋ], [teˈbæːjəˌkalˀə], [teˈbæːjəˌkaləlsə]",
    "oplyse": "[ˈʌbˌlyˀsə]",
    "opnå": "[ˈʌbˌnɔˀ]",
    "opstå": "[ˈʌbˌsdɔˀ]",
    "optræde": "[ˈʌbˌtʁεˀðə]",
    "ord": "[ˈoˀɐ̯]",
    "ost": "[ˈɔsd]",
    "over": "[ɒwʌ]",
    "overholde": "[ˈɒwʌˌhʌlˀə]",
    "overlade": "[ˈɒwʌˌlæˀðə], [beˈtʁoˀ], [ˈɒwʌˌgiˀ], [ˈɒwʌˌdʁɑˀwə]",
    "overleve": "[ˈɒwʌˌleˀvə]",
    "overraske": "[ˈɒwʌˌʁɑsgə], [ˈɒwʌˌʁɑsgəlse], [fʌˈbɑwˀsə], [fʌˈbɑwˀsəlse], [fʌˈbløfə], [fʌˈbløfəlse], [fʌˈɔnˀdʁʌ]",
    "overtage": "[-ˌtæˀ]",
    "overveje": "[ˈɒwʌˌvɑjˀə], [ˈɒwʌˌvɑjˀəlsə], [ˈgʁublə], [gʁublʌˈʁiˀ], [sbeguˈleˀʌ], [sbegulaˈɕoˀn]",
    "ovn": "[ˈɒwˀn], [kɔmˈfuɐ̯ˀ]",
    "pakke": "[ˈpɑgə]",
    "papir": "[paˈpiɐ̯ˀ]",
    "park": "[ˈpɑːg]",
    "pasta": "[ˈpasda]",
    "penge": "[ˈpεŋə], [kɔnˈtanˀd]",
    "person": "[pæɐ̯ˈsoˀn]",
    "pige": "[ˈpiːə]",
    "pingvin": "[peŋˈviˀn]",
    "pizza": "[ˈpidsa]",
    "planlægge": "[ˈplæːnˌlεgə]",
    "plaster": "[ˈplasdʌ]",
    "pleje": "[ˈplɑjə]",
    "pligt": "[ˈplegd], [fʌˈplegdəlsə]",
    "politi": "[poliˈtiˀ]",
    "posthus": "[ˈpʌsd-]",
    "presse": "[ˈpʁasə]",
    "pris": "[ˈpʁiˀs]",
    "problem": "[pʁoˈbleˀm]",
    "producere": "[pʁoduˈseˀʌ], [fɑbʁiˈkeˀʌ]",
    "professor": "[pʁoˈfεsʌ], [pʁofəˈsoːʌ]",
    "projekt": "[pʁoˈɕεgd]",
    "præsentation": "[pʁεsəntaˈɕoˀn]",
    "præsentere": "[pʁεsənˈteˀʌ], [entʁoduˈseˀʌ]",
    "prøve": "[ˈpʁœːwə], [fʌˈsøˀjə]",
    "pude": "[ˈpuːðə]",
    "på": "[ˈpɔˀ]",
    "påvirke": "[ˈpʌˌviɐ̯gə]",
    "pære": "[ˈpεːʌ]",
    "pølse": "[ˈpølsə]",
    "rabat": "[ʁɑˈbad]",
    "ramme": "[ˈʁɑmə]",
    "rapport": "[ʁɑˈpɒːd]",
    "reagere": "[ʁεaˈgeˀʌ]",
    "redde": "[ˈʁεðə], [ˈɔnˌsεdə]",
    "reducere": "[ʁεduˈseˀʌ]",
    "registrere": "[ʁεgiˈsdʁεˀʌ]",
    "regnbue": "[ˈʁɑjnˌbuːə]",
    "regning": "[ˈʁɑjneŋ]",
    "rejse": "[ˈʁɑjsə]",
    "ren": "[ˈʁεˀn]",
    "respektere": "[ʁεsbεgˈteˀʌ]",
    "restaurant": "[ʁεsdoˈʁɑŋ]",
    "resultat": "[ʁεsulˈtæˀd]",
    "ret": "[ˈʁad]",
    "rette": "[ˈʁadə]",
    "ride": "[ˈʁiːðə], [ˈʁεðˀ], [ˈʁεːðəd], [ˈʁiðneŋ]",
    "rig": "[ˈʁiˀ], [ˈkøːbə,døgdi], [ˈfadi]",
    "ringe": "[ˈʁεŋə]",
    "risikere": "[ʁisiˈkeˀʌ]",
    "risiko": "[ˈʁisiko]",
    "roman": "[ʁoˈmæˀn]",
    "rose": "[ˈʁoːsə]",
    "rotte": "[ˈʁʌdə], [ˈmuˀs]",
    "rulle": "[ˈʁulə], [ˈtʁilə]",
    "rund": "[ˈʁɔnˀ]",
    "ryg": "[ˈʁœg], [ˈlεnˀ]",
    "ryge": "[ˈʁyːə], [ˈʁʌjˀ], [ˈʁʌjəð]",
    "rykke": "[ˈʁœgə], [beˈvεˀjə]",
    "råbe": "[ˈʁɔːbə], [ˈʁɔːbʌ], [ˈʁʌbdə], [ˈʁʌbd]",
    "række": "[ˈʁagə]",
    "ræv": "[ˈʁεˀw]",
    "røre": "[ˈʁɶːʌ], [beˈʁɶˀʌ], [ˈføːle], [ˈmæɐ̯gə]",
    "salt": "[ˈsalˀd]",
    "samme": "[ˈsɑmə]",
    "sammenligne": "[ˈsɑmənˌliˀnə], [ˈfɒːˌhʌlˀ]",
    "sand": "[ˈsanˀ], [ˈsanˌheðˀ]",
    "sang": "[ˈsɑŋˀ]",
    "savne": "[ˈsɑwnə]",
    "se": "[ˈseˀ], [ˈkigə], [iˈɑgˌtæˀ], [beˈtʁɑgdə], [ˈanˌsguˀə], [ʌbsæɐ̯ˈveˀʌ], [ˈɒwʌˌvɔˀwə]",
    "sejle": "[ˈsɑjlə]",
    "sekund": "[seˈkɔnˀd]",
    "selvfølgelig": "[sεlˈføljəli]",
    "selvom": "[ˈsεlˀʌm]",
    "sende": "[ˈsεnə]",
    "seng": "[ˈsεŋˀ]",
    "servere": "[sæɐ̯ˈveˀʌ]",
    "sidde": "[ˈseðə], [ˈsεdə]",
    "side": "[ˈsiːðə]",
    "siden": "[ˈsiðən]",
    "sidste": "[ˈsisdə]",
    "sikre": "[ˈsegʁʌ]",
    "simpel": "[ˈsemˀbəl]",
    "situation": "[sidwaˈɕoˀn]",
    "skab": "[ˈsgæˀb]",
    "skade": "[ˈsgæːðə]",
    "skaffe": "[ˈsgɑfə]",
    "skam": "[ˈsgɑmˀ], [ˈsgɑmfulˀ]",
    "skarp": "[ˈsgɑːb]",
    "skat": "[ˈsgad]",
    "ske": "[ˈsgeˀ]",
    "skib": "[ˈsgiˀb]",
    "skifte": "[ˈsgifdə]",
    "skildpadde": "[ˈsgelˌpaðə]",
    "skinne": "[ˈsgenə]",
    "sko": "[ˈsgoˀ]",
    "skole": "[ˈsgoːlə]",
    "skov": "[ˈsgɒwˀ]",
    "skrige": "[ˈsgʁiːə], [ˈsgʁɑjˀ]",
    "skrive": "[ˈsgʁiːvə], [ˈsgʁiːvʌ], [ˈsgʁεwˀ], [ˈsgʁεːvəð]",
    "skræmme": "[ˈsgʁamə]",
    "skubbe": "[ˈsgɔbə]",
    "skuffe": "[ˈsgɔfə], [ˈsvegdə], [ˈæɐ̯wʁʌ], [beˈdʁœˀvə], [ˈsmæɐ̯də], [fʌˈtʁyˀðə], [ˈɑŋˀʌ]",
    "skuffelse": "[ˈsgɔfəlsə]",
    "skuffet": "[ˈsgɔfə]",
    "skulder": "[ˈsgulʌ]",
    "skulle": "[ˈsgulə], [ˈsgu], [ˈsga], [ˈsgal], ['sguləð]",
    "skulptur": "[sgulbˈtuɐ̯ˀ], [sgulbˈtøˀɐ̯], [ˈbeləðˌhɔgʌ]",
    "sky": "[ˈsgyˀ]",
    "skyde": "[ˈsgyːðə], [ˈsgøðˀ], [ˈsgud]",
    "skål": "[ˈsgɔˀl]",
    "skære": "[ˈsgεːʌ], [ˈsgɑˀ], [ˈsgɒːɒð], [ˈklebə]",
    "skærm": "[ˈsgæɐ̯ˀm]",
    "slags": "[ˈslɑgs]",
    "slange": "[ˈslɑŋə]",
    "slik": "[ˈsleg]",
    "slips": "[ˈslebs]",
    "slukke": "[ˈslɔgə]",
    "slutte": "[ˈsludə]",
    "slå": "[ˈslɔˀ], [ˈslɒˀ], [ˈsloˀ], ['sloəð]",
    "smage": "[ˈsmæːjə]",
    "smal": "[ˈsmalˀ], [ˈsnεwˀʌ], [ˈviðˀ], [ˈbʁεðˀ]",
    "smerte": "[ˈsmæɐ̯də], [ˈɔnˀ]",
    "smitte": "[ˈsmedə]",
    "smuk": "[ˈsmɔg], [ˈflʌd]",
    "smør": "[ˈsmɶɐ̯]",
    "snakke": "[ˈsnɑgə], [ˈtæːlə], [ˈsiː], [fʌˈtεlˀə], [beˈʁadə], [kʌnsdaˈteˀʌ], [æɐ̯ˈklεˀʌ], [ˈuðˌbʁyˀðə], [ˈuðˌʁɔˀbə]",
    "snart": "[ˈsnɑˀd], [ˈtiðli]",
    "sne": "[ˈsneˀ], [ˈsluð], [ˈtø,sneˀ]",
    "sofa": "[ˈsoːfa]",
    "sol": "[ˈsoˀl]",
    "sommer": "[ˈsʌmʌ]",
    "sommerfugl": "[ˈsʌmʌˌfuˀl]",
    "sorg": "[ˈsɒˀw]",
    "sove": "[ˈsɒwə]",
    "soveværelse": "[ˈsɒwə,væɐ̯ʌlsə]",
    "spare": "[ˈsbæːɐ̯]",
    "specifik": "[sbesiˈfig]",
    "spille": "[ˈsbelə], [ˈlɑjə]",
    "spise": "[ˈsbiːsə], [ˈεːðə], [fʌˈtεˀʌ]",
    "sprede": "[ˈsbʁεːðə], ['uðbʁεˀðə]",
    "sprog": "[ˈsbʁɔˀw]",
    "spænding": "[ˈsbεneŋ], [ˈsdʁɶmˀ]",
    "spørge": "[ˈsbɶɐ̯ʌ], [ˈbeːðə]",
    "spørgsmål": "[ˈsbɶɐ̯sˌmɔˀl]",
    "stamme": "[ˈsdɑmə]",
    "standse": "[ˈsdansə]",
    "station": "[sdaˈɕoˀn]",
    "stege": "[ˈsdɑjə], [soˈteˀʌ], [ˈsdεgd], [fʁiˈtyːʌ,sdεgd]",
    "stemme": "[ˈsdεmə]",
    "stige": "[ˈsdiːə]",
    "stikke": "[ˈsdegə]",
    "stille": "[ˈsdɔˀ], [ˈsdɒˀ], [ˈsdoˀ], [ˈsdɔːəð]",
    "stjæle": "[ˈsdjεːlə], [ˈsdjæˀl], [ˈsdjɔːləð]",
    "stol": "[ˈsdoˀl]",
    "stoppe": "[ˈsdʌbə], [ˈsdansə], [ˈsdansə], [ˈhʌlə]",
    "stor": "[ˈsdoˀɐ̯], [ˈsdɶɐ̯ʌ], [ˈsdoˀɐ̯]",
    "strand": "[ˈsdʁɑnˀ]",
    "strække": "[ˈsdʁagə]",
    "studere": "[sduˈdeˀʌ]",
    "studerende": "[sduˈdeˀʌnə]",
    "styre": "[ˈsdyːʌ], [ˈsdyɐ̯ˀ]",
    "styrke": "[ˈsdyɐ̯gə]",
    "stå": "[ˈsdɔˀ], [ˈsdɒˀ], [ˈsdoˀ], [ˈsdɔːəð]",
    "stærk": "[ˈsdæɐ̯g]",
    "støde": "[ˈsdøːðə], [koliˈdeˀʌ]",
    "størrelse": "[ˈsdɶɐ̯ʌlsə]",
    "støtte": "[ˈsdødə], [ˈsdødə], [ˈbɑgə], [ˈʌbˌbɑgneŋ]",
    "sukkersyge": "[ˈsɔgʌˈsyːə], [diaˈbeːdəs]",
    "sulten": "[ˈsuldən]",
    "suppe": "[ˈsɔbə]",
    "svag": "[ˈsvæˀj]",
    "svar": "[ˈsvɑˀ], [beˈsvɑˀɑlsə]",
    "svare": "[ˈsvɑːɑ], [beˈsvɑˀɑ]",
    "svinekød": "[ˈsviːnə,køð]",
    "svær": "[ˈsvεˀɐ̯], [ˈvansgəli]",
    "svømme": "[ˈsvœmə]",
    "sy": "[ˈsyˀ], [ˈsɔˀ]",
    "sygeplejerske": "[ˈsyːəˌplɑjˀʌsgə]",
    "synge": "[ˈsøŋə], [ˈsɑŋˀ], [ˈsɔŋəð]",
    "synke": "[ˈsøŋgə]",
    "system": "[syˈsdeˀm]",
    "sår": "[ˈsɒˀ]",
    "sæbe": "[ˈsεːbə]",
    "sælge": "[ˈsεljə]",
    "sæson": "[sεˈsʌŋ], [ˈɒːsˌtiðˀ]",
    "sætning": "[ˈsεdneŋ]",
    "sø": "[ˈsøˀ]",
    "sød": "[ˈsøðˀ], [ˈʁɑˀ], [ˈnudəð], [ˈkεˀɐ̯]",
    "søge": "[ˈleːðə], [ˈsøːjə]",
    "søn": "[ˈsœn]",
    "søster": "[ˈsøsdʌ]",
    "tabe": "[ˈtæːbə]",
    "tage": "[ˈtæˀ], [ˈtɑˀ], [ˈtoˀ], [ˈtæəð]",
    "takke": "[ˈtɑgə]",
    "tand": "[ˈtanˀ], [ˈtεnˀʌ], [ˈtanˌkøð], [ˈgɔmə]",
    "tandbørste": "[ˈtan,bɶɐ̯sdə]",
    "taske": "[ˈtasgə], [ˈpoːsə]",
    "tastatur": "[tasdaˈtuɐ̯ˀ], [ˈkiːˌbɒːd]",
    "tavle": "[ˈtɑwlə]",
    "teater": "[teˈæˀdʌ]",
    "tegne": "[ˈtɑjnə]",
    "telefon": "[teləˈfoˀn]",
    "terrasse": "[taˈʁɑsə]",
    "tid": "[ˈtiðˀ]",
    "tiger": "[ˈtiːʌ]",
    "til": "[ˈtel]",
    "tilbud": "[ˈtelˌbuð]",
    "tilbyde": "[ˈtelˌbyˀðə]",
    "time": "[ˈtiːmə]",
    "ting": "[ˈteŋˀ]",
    "tjene": "[ˈtjεːnə]",
    "tog": "[ˈtɔˀw]",
    "tom": "[ˈtʌmˀ]",
    "tomat": "[toˈmæˀd]",
    "torden": "[ˈtoɐ̯dən], [ˈlyˀn]",
    "torv": "[ˈtɒˀw]",
    "tradition": "[tʁɑdiˈɕoˀn], [tʁɑdiɕoˈnεlˀ]",
    "trappe": "[ˈtʁɑbə], [ˈʌbˌgɑŋˀ]",
    "trist": "[ˈtʁisd]",
    "tro": "[ˈtʁofasd]",
    "trykke": "[ˈtʁœgə], [ˈtasdə], [ˈslɔˀ]",
    "træ": "[ˈtʁεˀ]",
    "træde": "[ˈtʁεːðə], [ˈtʁʌdə]",
    "træffe": "[ˈtʁafə]",
    "trække": "[ˈtʁagə]",
    "træt": "[ˈtʁad], [ˈdøðtʁad], [ˈuðˌmadə], [ˈsœwni], [ˈtʁadˌheðˀ]",
    "trøje": "[ˈtʁʌjə], [ˈhεdə,tʁʌjə], [ˈswεdʌ], [ˈhεdə]",
    "tung": "[ˈtɔŋˀ], [ˈlεd]",
    "tunge": "[ˈtɔŋə]",
    "tunnel": "[ˈtɔnˀəl]",
    "turde": "[ˈtoːʌ], [ˈtɶɐ̯], [ˈtoːʌ], [ˈtuɐ̯də], [ˈvɔːvə]",
    "turkis": "[tyɐ̯ˈkiˀs]",
    "tvinge": "[ˈtveŋə]",
    "tydelig": "[ˈtyːðəli], [ˈklɑˀ], [ˈʌbˌlɑgd], [en,lyˀsənə], [ˈɔːbənˌlyˀs]",
    "tynd": "[ˈtønˀ], [ˈtyg]",
    "type": "[ˈtyːbə], [ˈslɑgs], [ˈɑˀd], [ˈsɒːd], [ˈɑwˌɑˀd], [vɑiˈanˀd]",
    "typisk": "[ˈtybisg]",
    "tå": "[ˈtɔˀ], [ˈtεˀɐ̯]",
    "tåle": "[ˈtɔːlə], [ˈuðˌhʌlˀə], [toləˈʁεˀʌ]",
    "tålmodig": "[tʌlˈmoˀði], [tʌlˈmoˀði,heðˀ]",
    "tælle": "[ˈtεlə], [ˈtaldə], [ˈtalˀd]",
    "tænde": "[ˈtεnə], [ˈslɔgə]",
    "tøj": "[ˈtʌj]",
    "tømme": "[ˈtœmə]",
    "tørklæde": "[ˈtɶɐ̯,klεːðə]",
    "tørre": "[ˈtɶɐ̯ʌ]",
    "tørstig": "[ˈtɶɐ̯sdi]",
    "uddanne": "[ˈuðˌdanˀə]",
    "uddannelse": "[ˈuðˌdanˀəlsə], [ˈuðˌdanˀə]",
    "uden": "[ˈuðən]",
    "udløse": "[ˈuðˌløˀsə], [ɑgtiˈveˀʌ], ['sεdə]",
    "udnytte": "[ˈuð,nødə]",
    "udsætte": "[ˈuðsεdə]",
    "udtale": "[ˈuð,tæːlə]",
    "udtrykke": "[ˈuðˌtʁœgə]",
    "udvide": "[ˈuðˌviðˀə]",
    "udvikle": "[ˈuðˌveglʌ]",
    "uge": "[ˈuːə]",
    "ugle": "[ˈuːlə]",
    "ulv": "[ˈulˀv]",
    "umulig": "[uˈmuˀli]",
    "under": "[ˈɔnˀʌ]",
    "undgå": "[ˈɔnˌgɔˀ]",
    "ung": "[ˈɔŋˀ], [ˈøŋʁʌ], [ˈøŋˀsd]",
    "ungdom": "[ˈɔŋˌdʌmˀ]",
    "universitet": "[univæɐ̯siˈteˀd]",
    "ur": "[ˈuɐ̯ˀ]",
    "valg": "[ˈvalˀ]",
    "valuta": "[vaˈluta], [obligaˈɕoˀn], [ˈɑgɕə], [væɐ̯ˈdi,paˈpiɐ̯ˀ]",
    "vand": "[ˈvanˀ]",
    "vare": "[ˈvɑːɑ]",
    "variere": "[vɑiˈeˀʌ], [ˈvεgslə], [flugtuˈeˀʌ]",
    "varm": "[ˈvɑˀm], [ˈluˀn], [ˈkʌlˀ], [ˈkøːli]",
    "ved": "[ve]",
    "vedtage": "[ˈveðˌtæˀ]",
    "veje": "[ˈvɑjə], [ˈvεgd]",
    "vejr": "[ˈvεˀɐ̯]",
    "ven": "[ˈvεn], [vεnˈenə]",
    "vente": "[ˈvεndə]",
    "vide": "[ˈviːðə], [ˈviːðən], [ˈviːðənə], [ˈkεnə], [ˈkεnˌsgæˀb]",
    "viden": "[ˈviːðən]",
    "video": "[ˈviˀdjo]",
    "vigtig": "[ˈvegdi], [ˈliːəˌgylˀdi]",
    "ville": "[ˈvilə], [ˈve], [ˈvilə], [ˈviləð]",
    "vinde": "[ˈvenə], [ˈsɑjʁʌ], [beˈsɑjˀʁʌ], [ˈɒwʌ,venə]",
    "vindue": "[ˈvendu]",
    "vinke": "[ˈveŋgə]",
    "vinter": "[ˈvenˀdʌ]",
    "virke": "[ˈviɐ̯gə], [fɔŋˈgeˀʌ]",
    "vise": "[ˈviːsə]",
    "vred": "[ˈvʁεð]",
    "vulkan": "[vulˈkæˀn], [vulˈkæˀn,uðˌbʁuð], [vulˈkæˀnsg]",
    "vurdere": "[vuɐ̯ˈdeˀʌ], [vuɐ̯ˈdeˀɐ̯eŋ], [beˈdœmˀə], [beˈdœmˀəlsə], [evaluˈeˀʌ], [evaluˈeˀɐ̯eŋ]",
    "vågne": "[ˈvɔwnə], [ˈsdɔˀ], [ˈsdɒˀ], [ˈsdoˀ], [ˈsdɔːəð], [ˈvεgə]",
    "væg": "[ˈvεˀg]",
    "vække": "[ˈvεgə]",
    "vælge": "[ˈvεljə]",
    "vælte": "[ˈvεldə]",
    "være": "[ˈvεːʌ], [ˈæɐ̯], [ˈvɑ], [ˈvεːʌð]",
    "værsgo": "[ˈvæɐ̯ˈsgoˀ]",
    "weekend": "[ˈviːˌgεnˀd]",
    "yde": "[ˈyːðə]",
    "yoghurt": "[ˈjoˌguɐ̯ˀd]",
    "åben": "[ˈɔːbən]",
    "åbne": "[ˈɔːbnə], [ˈlɔgə]",
    "år": "[ˈɒˀ]",
    "æble": "[ˈεːblə]",
    "ærlig": "[ˈæɐ̯li], [ˈæɐ̯liˌheðˀ]",
    "ø": "[ˈøˀ]",
    "ødelægge": "[ˈøːðəˌlεgə], [desdʁuˈeˀʌ], [teˈendəðˌgɶˀʌ], [ˈuð,slεdə], [ˈuð,ʁɑ,deˀʌ]",
    "øge": "[øˀjə], [fʌˈøˀjə], [ˈmensgə], [fʌˈmenˀsgə], [ˈuðˌviðˀə], [εgspanˈdeˀʌ], [ˈuð,bygə], ['enˌsgʁaŋˀgə], [fʌˈsnεwˀʁʌ], ['en,snεwˀʁʌ], [ˈhεːvə], [ˈsεdə], [fʌˈhʌjˀə], [ˈsεŋgə], [ˈsεdə], [ˈsdiːə], [ˈfalə], [ˈdæːlə]",
    "øje": "[ˈʌjə]",
    "øl": "[ˈøl]",
    "ønske": "[ˈønsgə]",
  },
};
